variables:
  # Replace this name with that of the Azure service connection in your DevOps project
  ConnectedServiceName: 'yuvraj_dighwara_asp_Linux_centralus_0'

  # Replace this name to match the name of the App Service you created earlier
  WebAppName: 'yuvraj3010-flaskpipelines'


trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'
    architecture: 'x64'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
